### ISSUE TITLE
11ac

### ISSUE THREAD

**Issue by ghost** [travelping/freewtp#8]
Can you support 11ac?

**Comment by RoadRunnr** [comment]
Yes we can, but unfortunately we do not right now.

What we do support is 802.11n (HT) which works on both 2.4GHz and 5Ghz with 20MHz wide channels. Since most WiFi radio support only MCS up to index 15, this will top out at 144Mbit/s (see http://www.wlanpros.com/mcs-index-802-11n-802-11ac-chart-3/ for a full list)

Adding some vendor information elements to transport the capability and configure the radio is relatively simple.

Supporting 80Mhz and 160MHz wide channels requires DFS and TPC (in most countries). Most of this done in the kernel driver, but we still need to trigger it, report the results back to AC and have the AC take the required actions.

**Comment by ghost** [comment]
Why not continue to develop the CAPWAP(AC)?

**Comment by RoadRunnr** [comment]
CAPWAP AC is at:
* https://github.com/travelping/capwap for the control part written in Erlang,
* https://github.com/travelping/capwap-dp for the datapath,
* https://github.com/travelping/ergw-capwap-node to simplify the packaging of the Erlang control part

Erlang is our language of choice for protocol control implementation.
